import test from 'node:test';
import assert from 'node:assert/strict';
import { access, readFile } from 'node:fs/promises';
const [settingsDialog, settings, main, index] = await Promise.all(['ui/src/layout/SettingsDialog.tsx', 'ui/src/lib/terminal-settings.ts', 'ui/src/main.tsx', 'ui/index.html'].map(file => readFile(new URL(`../${file}`, import.meta.url), 'utf8')));
test('settings navigation provides a rendered icon for every section', () => { assert.match(settingsDialog, /data-settings-tab="font"[\s\S]*<Type/); assert.match(settingsDialog, /data-settings-tab="groups"[\s\S]*<Folder/); });
test('settings uses controlled shadcn controls and React state', () => { assert.match(settingsDialog, /useState/); assert.match(settingsDialog, /<Select/); assert.match(settingsDialog, /<Input/); assert.match(settingsDialog, /<Card/); assert.doesNotMatch(settingsDialog, /<select\b/); });
test('settings preserves persistence, all-terminal application, and async font chunking', () => { assert.match(settings, /localStorage\.getItem\(STORAGE_KEY\)/); assert.match(settings, /localStorage\.setItem\(STORAGE_KEY/); assert.match(settings, /applyToAllTerminals/); assert.match(settings, /FONT_CHUNK_SIZE = 12/); assert.match(settings, /await yieldToBrowser\(\)/); assert.match(settings, /warmSystemFontPresets/); });
test('old settings loaders are gone', async () => { await assert.rejects(access(new URL('../assets', import.meta.url))); await assert.rejects(access(new URL('../views', import.meta.url))); assert.doesNotMatch(main, /assets\/css/); assert.doesNotMatch(index, /views|assets/); });
test('Nerd Font is bundled and declared in the React stylesheet', async () => { const css = await readFile(new URL('../ui/src/index.css', import.meta.url), 'utf8'); assert.match(css, /@font-face/); assert.match(css, /JetBrainsMonoNerdFontMono-Regular\.ttf/); assert.match(css, /JetBrainsMonoNerdFontMono-Bold\.ttf/); await readFile(new URL('../ui/src/assets/fonts/JetBrainsMonoNerdFontMono-Regular.ttf', import.meta.url)); await readFile(new URL('../ui/src/assets/fonts/JetBrainsMonoNerdFontMono-Bold.ttf', import.meta.url)); });
